server:
  port: 8082
  servlet:
    context-path: /api
spring:
  application:
    name: picture-cloud
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-center
    username: root
    password: 123456